server.port: 3000

spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/kob?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
